spring:
  application:
    name: CallAutomation_OutboundCalling

server:
  port: 8080

acs:
  connectionstring: endpoint=https://isuraconnectortest.unitedstates.communication.azure.com/;accesskey=gRt4jvKrU6Wr/lKoXP6urJhHCi2OW1barEXBq7HT00EgT5XFKh6bazEJtFhcfLzIYmYXeQjh0FWL4zoCm16yqA==
  basecallbackuri: https://17hmwrdx.usw3.devtunnels.ms:8080
  callerphonenumber: "+18336421880"
  targetphonenumber: "+15624728312"
